/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountDetails: typeof import('./components/AccountDetails.vue')['default']
    AccountInfo: typeof import('./components/AccountInfo.vue')['default']
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    BlockDetails: typeof import('./components/BlockDetails.vue')['default']
    CountUp: typeof import('./components/CountUp.vue')['default']
    CreateTokenModal: typeof import('./components/CreateTokenModal.vue')['default']
    DepositModal: typeof import('./components/DepositModal.vue')['default']
    MeerayTransaction: typeof import('./components/MeerayTransaction.vue')['default']
    NavDropdown: typeof import('./components/NavDropdown.vue')['default']
    NoSidechainAccountModal: typeof import('./components/NoSidechainAccountModal.vue')['default']
    PairIcon: typeof import('./components/PairIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SteemTransaction: typeof import('./components/SteemTransaction.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    ToastContainer: typeof import('./components/ToastContainer.vue')['default']
    TokenIcon: typeof import('./components/TokenIcon.vue')['default']
  }
}
